template_project/template_app/urls.py
import imp
from django.conf.urls import url 
from template_app import views

# Template tagging 
app_name = 'template_app'

urlpatterns = [
    url(r'^relative/$',views.relative,name='relative'),
    url(r'^other/$',views.other,name='other'), 
]

template_project/template_project/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from template_app import views
 
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url('admin/', admin.site.urls),
    url(r'^template_app/',include('template_app.urls'))
]
    

template_project/template_app/models.py
from django.db import models

# Create your models here.

template_project/template_app/views.py
from difflib import context_diff
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict = {'text':'Hello World!','number':100}
    return render(request,'template_app/index.html',context_dict)

def other(request):
    return render(request,'template_app/other.html')

def relative(request):
    return render(request,'template_app/relative_url_template.html')

     

template_project/templates/template_app/basic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'index' %}">BRAND</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">Admin</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'template_app:other' %}">Other</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

    <div class="container">

        {% block body_block %}
        <!-- Anything outside of this it will be inherited if you extend! -->
        {% endblock %}

    </div>



</body>
</html> 

template_project/templates/template_app/index.html
<!DOCTYPE html>
{% extends "template_app/basic.html" %}
    {% block body_block %}
    <h1>WELCOME TO HOMEPAGE!</h1>
    <h2>This is index.html page showing!</h2>
    <h1> {{ text|cut:"World" }}</h1>
    <h1>{{ number|add:"99" }}</h1>
    {% endblock %}
 

template_project/templates/template_app/other.html
<!DOCTYPE html> 
{% extends "template_app/basic.html"%}
  {% block body_block %}
    <h1>WELCOME TO OTHER!</h1>
    <h2>This is an example of template inheritence!</h2>
  {% endblock %}

template_project/templates/template_app/relative_url_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
</head>
<body>
    <h1>WELCOME TO RELATIVE URL TEMPLATE!</h1>
    <a href="{% url  'template_app:other'  %}">THE OTHER PAGE</a>
    <a href="{% url 'admin:index' %}">LINK TO ADMIN</a>
    <a href="{% url 'index'  %}">LINK TO INDEX</a>
</body>
</html>  